spring:
  datasource:
    url: jdbc:h2:mem:h2_database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jackson:
    serialization:
      indent_output: true


