spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?createDatabaseIfNotExist=true
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect