spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_database
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect